create table "public"."purchase" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default (now() AT TIME ZONE 'utc'::text),
    "date" timestamp with time zone
);


create table "public"."purchase_item" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "code" text,
    "price" double precision,
    "amount" double precision,
    "purchase_id" bigint,
    "description" text,
    "category" text
);


CREATE UNIQUE INDEX purchase_date_key ON public.purchase USING btree (date);

CREATE UNIQUE INDEX purchase_item_pkey ON public.purchase_item USING btree (id);

CREATE UNIQUE INDEX purchase_pkey ON public.purchase USING btree (id);

alter table "public"."purchase" add constraint "purchase_pkey" PRIMARY KEY using index "purchase_pkey";

alter table "public"."purchase_item" add constraint "purchase_item_pkey" PRIMARY KEY using index "purchase_item_pkey";

alter table "public"."purchase" add constraint "purchase_date_key" UNIQUE using index "purchase_date_key";

alter table "public"."purchase_item" add constraint "purchase_item_purchase_id_fkey" FOREIGN KEY (purchase_id) REFERENCES purchase(id) not valid;

alter table "public"."purchase_item" validate constraint "purchase_item_purchase_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.get_purchase_overview(start_date date, end_date date)
 RETURNS TABLE(code text, description text, total_amount double precision)
 LANGUAGE plpgsql
AS $function$
BEGIN
    RETURN QUERY
    SELECT
        pi.code, 
        MAX(pi.description) AS description,
        SUM(pi.amount) AS total_amount
    FROM
        purchase_item pi
    JOIN
        purchase p ON pi.purchase_id = p.id
    WHERE
        p.date >= start_date AND p.date < end_date
    GROUP BY
        pi.code
    ORDER BY
        total_amount DESC;
END;
$function$
;


grant delete on table "public"."purchase" to "anon";

grant insert on table "public"."purchase" to "anon";

grant references on table "public"."purchase" to "anon";

grant select on table "public"."purchase" to "anon";

grant trigger on table "public"."purchase" to "anon";

grant truncate on table "public"."purchase" to "anon";

grant update on table "public"."purchase" to "anon";

grant delete on table "public"."purchase" to "authenticated";

grant insert on table "public"."purchase" to "authenticated";

grant references on table "public"."purchase" to "authenticated";

grant select on table "public"."purchase" to "authenticated";

grant trigger on table "public"."purchase" to "authenticated";

grant truncate on table "public"."purchase" to "authenticated";

grant update on table "public"."purchase" to "authenticated";

grant delete on table "public"."purchase" to "service_role";

grant insert on table "public"."purchase" to "service_role";

grant references on table "public"."purchase" to "service_role";

grant select on table "public"."purchase" to "service_role";

grant trigger on table "public"."purchase" to "service_role";

grant truncate on table "public"."purchase" to "service_role";

grant update on table "public"."purchase" to "service_role";

grant delete on table "public"."purchase_item" to "anon";

grant insert on table "public"."purchase_item" to "anon";

grant references on table "public"."purchase_item" to "anon";

grant select on table "public"."purchase_item" to "anon";

grant trigger on table "public"."purchase_item" to "anon";

grant truncate on table "public"."purchase_item" to "anon";

grant update on table "public"."purchase_item" to "anon";

grant delete on table "public"."purchase_item" to "authenticated";

grant insert on table "public"."purchase_item" to "authenticated";

grant references on table "public"."purchase_item" to "authenticated";

grant select on table "public"."purchase_item" to "authenticated";

grant trigger on table "public"."purchase_item" to "authenticated";

grant truncate on table "public"."purchase_item" to "authenticated";

grant update on table "public"."purchase_item" to "authenticated";

grant delete on table "public"."purchase_item" to "service_role";

grant insert on table "public"."purchase_item" to "service_role";

grant references on table "public"."purchase_item" to "service_role";

grant select on table "public"."purchase_item" to "service_role";

grant trigger on table "public"."purchase_item" to "service_role";

grant truncate on table "public"."purchase_item" to "service_role";

grant update on table "public"."purchase_item" to "service_role";


