name: Scrape and Upload

on:
  workflow_dispatch:

jobs:
  carrefour-bot:
    name: Test puppeteer
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Install packages
        working-directory: scripts/carrefour
        run: npm install

      - name: Test action
        uses: tj-actions/puppeteer@v5
        id: puppeteer-test
        with:
          files: scripts/carrefour/bot.js
