name: Scrape and Upload

on:
  workflow_dispatch:

jobs:
  carrefour-bot:
    name: Test puppeteer
    runs-on: ubuntu-latest
    env:
      API_ENDPOINT: "${{ secrets.API_ENDPOINT }}" # Set the environment variable for the job

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "latest"

      - name: Install packages
        working-directory: scripts/carrefour
        run: npm ci

      - name: Run Puppeteer Script
        working-directory: scripts/carrefour
        run: node bot.js
        env:
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
